In [1]:
from Bio.PDB import *
#from functools import reduce
import numpy as np
import nglview as nv
from numpy import save
import json
"""
######################################################################################
# used to fetch PDB/mmCIF file from PDB website                                      #
# filename=PDB id                                                                    #
#                                                                                    #
# in just change the filename and re-run the code, this will give you                #
# vectorized protein files with <PDBid>-<chainid>-<x or y>-.npx for feeding the model#
# as well as the expected output of the model                                        #
######################################################################################
"""
filename = '1fat'#<-although the id you saw on website is capatial letter, please enter small letter here

# setting up parser and fetcher of PDB
parser = MMCIFParser()
pdbl=PDBList()
pdbl.retrieve_pdb_file(filename)


Structure exists: '/home/edward/Desktop/PDBVectorize/fa/1fat.cif' 


'/home/edward/Desktop/PDBVectorize/fa/1fat.cif'

In [2]:
#Creating object that usable in python from json string of amino acid properties
aap='{"A": {"hydrophobicity": 0.62,"hydrophilicity": -0.5,"hydrogenBond": 2,"volumeOfSideChains": 27.5,"polarity": 8.1,"polarizability": 0.046,"solventAccessibleSurfaceArea": 1.181,"netChargeIndexOfSideChains": 0.007187,"averageMass": 71.0788},"C": {"hydrophobicity": 0.29,"hydrophilicity": -1,"hydrogenBond": 2,"volumeOfSideChains": 44.6,"polarity": 5.5,"polarizability": 0.128,"solventAccessibleSurfaceArea": 1.461,"netChargeIndexOfSideChains": -0.03661,"averageMass": 103.1388},"D": {"hydrophobicity": -0.9,"hydrophilicity": 3,"hydrogenBond": 4,"volumeOfSideChains": 40,"polarity": 13,"polarizability": 0.105,"solventAccessibleSurfaceArea": 1.587,"netChargeIndexOfSideChains": -0.2382,"averageMass": 115.0886},"E": {"hydrophobicity": -0.74,"hydrophilicity": 3,"hydrogenBond": 4,"volumeOfSideChains": 62,"polarity": 12.3,"polarizability": 0.151,"solventAccessibleSurfaceArea": 1.862,"netChargeIndexOfSideChains": 0.006802,"averageMass": 129.1155},"F": {"hydrophobicity": 1.19,"hydrophilicity": -2.5,"hydrogenBond": 2,"volumeOfSideChains": 115.5,"polarity": 5.2,"polarizability": 0.29,"solventAccessibleSurfaceArea": 2.228,"netChargeIndexOfSideChains": 0.037552,"averageMass": 147.1766},"G": {"hydrophobicity": 0.48,"hydrophilicity": 0,"hydrogenBond": 2,"volumeOfSideChains": 0,"polarity": 9,"polarizability": 0,"solventAccessibleSurfaceArea": 0.881,"netChargeIndexOfSideChains": 0.179052,"averageMass": 57.0519},"H": {"hydrophobicity": -0.4,"hydrophilicity": -0.5,"hydrogenBond": 4,"volumeOfSideChains": 79,"polarity": 10.4,"polarizability": 0.23,"solventAccessibleSurfaceArea": 2.025,"netChargeIndexOfSideChains": -0.01069,"averageMass": 137.1411},"I": {"hydrophobicity": 1.38,"hydrophilicity": -1.8,"hydrogenBond": 2,"volumeOfSideChains": 93.5,"polarity": 5.2,"polarizability": 0.186,"solventAccessibleSurfaceArea": 1.81,"netChargeIndexOfSideChains": 0.021631,"averageMass": 113.1594},"K": {"hydrophobicity": -1.5,"hydrophilicity": 3,"hydrogenBond": 2,"volumeOfSideChains": 100,"polarity": 11.3,"polarizability": 0.219,"solventAccessibleSurfaceArea": 2.258,"netChargeIndexOfSideChains": 0.017708,"averageMass": 128.1741},"L": {"hydrophobicity": 1.06,"hydrophilicity": -1.8,"hydrogenBond": 2,"volumeOfSideChains": 93.5,"polarity": 5.2,"polarizability": 0.186,"solventAccessibleSurfaceArea": 1.931,"netChargeIndexOfSideChains": 0.051672,"averageMass": 113.1594	},"M": {"hydrophobicity": 0.64,"hydrophilicity": -1.3,"hydrogenBond": 2,"volumeOfSideChains": 94.1,"polarity": 5.7,"polarizability": 0.221,"solventAccessibleSurfaceArea": 2.034,"netChargeIndexOfSideChains": 0.002683,"averageMass": 131.1986},"N": {"hydrophobicity": -0.78,"hydrophilicity": 2,"hydrogenBond": 4,"volumeOfSideChains": 58.7,"polarity": 11.6,"polarizability": 0.134,"solventAccessibleSurfaceArea": 1.655,"netChargeIndexOfSideChains": 0.005392,"averageMass": 114.1039},"P": {"hydrophobicity": 0.12,"hydrophilicity": 0,"hydrogenBond": 2,"volumeOfSideChains": 41.9,"polarity": 8,"polarizability": 0.131,"solventAccessibleSurfaceArea": 1.468,"netChargeIndexOfSideChains": 0.239531,"averageMass": 97.1167},"Q": {"hydrophobicity": -0.85,"hydrophilicity": 0.2,"hydrogenBond": 4,"volumeOfSideChains": 80.7,"polarity": 10.5,"polarizability": 0.18,"solventAccessibleSurfaceArea": 1.932,"netChargeIndexOfSideChains": 0.049211,"averageMass": 128.1307},"R": {"hydrophobicity": -2.53,"hydrophilicity": 3,"hydrogenBond": 4,"volumeOfSideChains": 105,"polarity": 10.5,"polarizability": 0.18,"solventAccessibleSurfaceArea": 1.932,"netChargeIndexOfSideChains": 0.49211,"averageMass": 156.1875},"S": {"hydrophobicity": -0.18,"hydrophilicity": 0.3,"hydrogenBond": 4,"volumeOfSideChains": 29.3,"polarity": 9.2,"polarizability": 0.062,"solventAccessibleSurfaceArea": 1.298,"netChargeIndexOfSideChains": 0.004627,"averageMass": 87.0782},"T": {"hydrophobicity": -0.05,"hydrophilicity": -0.4,"hydrogenBond": 4,"volumeOfSideChains": 51.3,"polarity": 9.6,"polarizability": 0.108,"solventAccessibleSurfaceArea": 1.525,"netChargeIndexOfSideChains": 0.003352,"averageMass": 101.1051},"V": {"hydrophobicity": 1.08,"hydrophilicity": -1.5,"hydrogenBond": 2,"volumeOfSideChains": 71.5,"polarity": 5.9,"polarizability": 0.14,"solventAccessibleSurfaceArea": 1.645,"netChargeIndexOfSideChains": 0.057004,"averageMass": 99.1326},"W": {"hydrophobicity": 0.81,"hydrophilicity": -3.4,"hydrogenBond": 3,"volumeOfSideChains": 145.5,"polarity": 5.4,"polarizability": 0.409,"solventAccessibleSurfaceArea": 2.663,"netChargeIndexOfSideChains": 0.037977,"averageMass": 186.2132},"Y": {"hydrophobicity": 0.26,"hydrophilicity": -2.3,"hydrogenBond": 3,"volumeOfSideChains": 117.3,"polarity": 6.2,"polarizability": 0.298,"solventAccessibleSurfaceArea": 2.368,"netChargeIndexOfSideChains": 0.023599,"averageMass": 163.1760}}'
aapo=json.loads(aap)
aapo["A"]

{u'averageMass': 71.0788,
 u'hydrogenBond': 2,
 u'hydrophilicity': -0.5,
 u'hydrophobicity': 0.62,
 u'netChargeIndexOfSideChains': 0.007187,
 u'polarity': 8.1,
 u'polarizability': 0.046,
 u'solventAccessibleSurfaceArea': 1.181,
 u'volumeOfSideChains': 27.5}

In [3]:
#parsing the fetched PDB file in this case mmcif file also see its 3D structure if the nv is working fine
structure = parser.get_structure(filename, './'+filename[1:3]+'/'+filename+'.cif')
view =nv.show_biopython(structure)
view

/home/edward/.local/lib/python2.7/site-packages/Bio/PDB/StructureBuilder.py:92: PDBConstructionWarning: WARNING: Chain A is discontinuous at line 7168.
  PDBConstructionWarning,
/home/edward/.local/lib/python2.7/site-packages/Bio/PDB/StructureBuilder.py:92: PDBConstructionWarning: WARNING: Chain B is discontinuous at line 7184.
  PDBConstructionWarning,
/home/edward/.local/lib/python2.7/site-packages/Bio/PDB/StructureBuilder.py:92: PDBConstructionWarning: WARNING: Chain C is discontinuous at line 7200.
  PDBConstructionWarning,
/home/edward/.local/lib/python2.7/site-packages/Bio/PDB/StructureBuilder.py:92: PDBConstructionWarning: WARNING: Chain D is discontinuous at line 7216.
  PDBConstructionWarning,
/home/edward/.local/lib/python2.7/site-packages/Bio/PDB/StructureBuilder.py:92: PDBConstructionWarning: WARNING: Chain A is discontinuous at line 7232.
  PDBConstructionWarning,
/home/edward/.local/lib/python2.7/site-packages/Bio/PDB/StructureBuilder.py:92: PDBConstructionWarning: WARNIN

NGLWidget()

In [4]:
#rubbish for testing the biopython library
for model in structure:
    #print('@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@')
   # print(model)
    MODEL=model
   # for chain in model:
      #  print('^^^^^^^^^^^^^^^^')
     #   print(chain)
    #    for residue in chain:
   #         print('**')
  #          print(residue)
 #           for atom in residue:
#                print(atom)


    

In [5]:
# setting up function for building the Y vector from with the goddamnit library DSSP

from Bio.PDB.DSSP import DSSP
dssp = DSSP(MODEL, './'+filename[1:3]+'/'+filename+'.cif', dssp='mkdssp')
a_key=list(dssp.keys())[1]
dssp[a_key]

def BuildVectorY(id1,id2):
    dsspTuple=dssp[(id1,id2)]
    yvec=None
    if dsspTuple[2]=='H' or dsspTuple[2]=='G' or dsspTuple[2]=='I':
        yvec=np.array([[1,0,0,0]])
    elif dsspTuple[2]=='B' or dsspTuple[2]=='E':
        yvec=np.array([[0,1,0,0]])
    elif dsspTuple[2]=='T' or dsspTuple[2]=='S':
        yvec=np.array([[0,0,1,0]])
    else:
        yvec=np.array([[0,0,0,1]])
    phipsi=np.array([[dsspTuple[4],dsspTuple[5]]])
    yvec=np.append(yvec,phipsi, axis=1)
    return yvec
    

In [6]:
#generate numpy matrix and export to .npy file

for model in structure:
    for chain in model:
        chainarr=None
        finalYarr=None
        for res in chain.get_residues():
            resname=res.get_resname()
            finalArr=None
            #print(finalYArr)
            #print(finalYArr is None)
            #print(BuildVectorY(chain.id,res.id))
            #finalYArr=BuildVectorY(chain.id,res.id)
            #print(finalYArr)
            #print(finalYArr is None)
            #print('-------------------')
            
            #convert the 3 letter code to a matrix of 20*9
            if resname == 'ALA':
                obj=aapo['A']
                resarr=np.array([[[obj['averageMass'],obj['hydrogenBond'],obj['hydrophilicity'],obj['hydrophobicity'],obj['netChargeIndexOfSideChains'],obj['polarity'],obj['polarizability'],obj['solventAccessibleSurfaceArea'],obj['volumeOfSideChains']]]])
                zeros=np.zeros((1,1,9))
                
                ## build Ys
                if(finalYarr is None):
                    finalYarr=BuildVectorY(chain.id,res.id)
                else:
                    finalYarr=np.append(finalYarr,BuildVectorY(chain.id,res.id), axis=0)
                
                ##buildXs
                for x in range(20):
                    if x == 0:
                        finalArr=np.append(resarr,zeros, axis=1)
                    else:
                        finalArr=np.append(finalArr,zeros,  axis=1)
            elif resname == 'ARG':
                obj=aapo['R']
                resarr=np.array([[[obj['averageMass'],obj['hydrogenBond'],obj['hydrophilicity'],obj['hydrophobicity'],obj['netChargeIndexOfSideChains'],obj['polarity'],obj['polarizability'],obj['solventAccessibleSurfaceArea'],obj['volumeOfSideChains']]]])
                zeros=np.zeros((1,1,9))
                 ## build Ys
                if(finalYarr is None):
                    finalYarr=BuildVectorY(chain.id,res.id)
                else:
                    finalYarr=np.append(finalYarr,BuildVectorY(chain.id,res.id), axis=0)
                
                #buildXs
                for x in range(20):
                    if x == 1:
                        finalArr=np.append(finalArr,resarr, axis=1)
                    elif x==0:
                        finalArr=np.append(zeros,zeros, axis=1)
                    else:
                        finalArr=np.append(finalArr,zeros,  axis=1)
            elif resname == 'ASN':
                obj=aapo['N']
                resarr=np.array([[[obj['averageMass'],obj['hydrogenBond'],obj['hydrophilicity'],obj['hydrophobicity'],obj['netChargeIndexOfSideChains'],obj['polarity'],obj['polarizability'],obj['solventAccessibleSurfaceArea'],obj['volumeOfSideChains']]]])
                zeros=np.zeros((1,1,9))
                 ## build Ys
                if(finalYarr is None):
                    finalYarr=BuildVectorY(chain.id,res.id)
                else:
                    finalYarr=np.append(finalYarr,BuildVectorY(chain.id,res.id), axis=0)
                
                #buildXs
                for x in range(20):
                    if x == 2:
                        finalArr=np.append(finalArr,resarr, axis=1)
                    elif x==0:
                        finalArr=np.append(zeros,zeros, axis=1)
                    else:
                        finalArr=np.append(finalArr,zeros,  axis=1)
            elif resname == 'ASP':
                obj=aapo['D']
                resarr=np.array([[[obj['averageMass'],obj['hydrogenBond'],obj['hydrophilicity'],obj['hydrophobicity'],obj['netChargeIndexOfSideChains'],obj['polarity'],obj['polarizability'],obj['solventAccessibleSurfaceArea'],obj['volumeOfSideChains']]]])
                zeros=np.zeros((1,1,9))
                 ## build Ys
                if(finalYarr is None):
                    finalYarr=BuildVectorY(chain.id,res.id)
                else:
                    finalYarr=np.append(finalYarr,BuildVectorY(chain.id,res.id), axis=0)
                #buildXs
                for x in range(20):
                    if x == 3:
                        finalArr=np.append(finalArr,resarr, axis=1)
                    elif x==0:
                        finalArr=np.append(zeros,zeros, axis=1)
                    else:
                        finalArr=np.append(finalArr,zeros,  axis=1)
            elif resname == 'CYS':
                obj=aapo['C']
                resarr=np.array([[[obj['averageMass'],obj['hydrogenBond'],obj['hydrophilicity'],obj['hydrophobicity'],obj['netChargeIndexOfSideChains'],obj['polarity'],obj['polarizability'],obj['solventAccessibleSurfaceArea'],obj['volumeOfSideChains']]]])
                zeros=np.zeros((1,1,9))
                 ## build Ys
                if(finalYarr is None):
                    finalYarr=BuildVectorY(chain.id,res.id)
                else:
                    finalYarr=np.append(finalYarr,BuildVectorY(chain.id,res.id), axis=0)
                #buildXs
                for x in range(20):
                    if x == 4:
                        finalArr=np.append(finalArr,resarr, axis=1)
                    elif x==0:
                        finalArr=np.append(zeros,zeros, axis=1)
                    else:
                        finalArr=np.append(finalArr,zeros,  axis=1)
            elif resname == 'GLU':
                obj=aapo['E']
                resarr=np.array([[[obj['averageMass'],obj['hydrogenBond'],obj['hydrophilicity'],obj['hydrophobicity'],obj['netChargeIndexOfSideChains'],obj['polarity'],obj['polarizability'],obj['solventAccessibleSurfaceArea'],obj['volumeOfSideChains']]]])
                zeros=np.zeros((1,1,9))
                 ## build Ys
                if(finalYarr is None):
                    finalYarr=BuildVectorY(chain.id,res.id)
                else:
                    finalYarr=np.append(finalYarr,BuildVectorY(chain.id,res.id), axis=0)
                #buildXs
                for x in range(20):
                    if x == 5:
                        finalArr=np.append(finalArr,resarr, axis=1)
                    elif x==0:
                        finalArr=np.append(zeros,zeros, axis=1)
                    else:
                        finalArr=np.append(finalArr,zeros,  axis=1)
            elif resname == 'GLN':
                obj=aapo['Q']
                resarr=np.array([[[obj['averageMass'],obj['hydrogenBond'],obj['hydrophilicity'],obj['hydrophobicity'],obj['netChargeIndexOfSideChains'],obj['polarity'],obj['polarizability'],obj['solventAccessibleSurfaceArea'],obj['volumeOfSideChains']]]])
                zeros=np.zeros((1,1,9))
                 ## build Ys
                if(finalYarr is None):
                    finalYarr=BuildVectorY(chain.id,res.id)
                else:
                    finalYarr=np.append(finalYarr,BuildVectorY(chain.id,res.id), axis=0)
                #buildXs
                for x in range(20):
                    if x == 6:
                        finalArr=np.append(finalArr,resarr, axis=1)
                    elif x==0:
                        finalArr=np.append(zeros,zeros, axis=1)
                    else:
                        finalArr=np.append(finalArr,zeros,  axis=1)
            elif resname == 'GLY':
                obj=aapo['G']
                resarr=np.array([[[obj['averageMass'],obj['hydrogenBond'],obj['hydrophilicity'],obj['hydrophobicity'],obj['netChargeIndexOfSideChains'],obj['polarity'],obj['polarizability'],obj['solventAccessibleSurfaceArea'],obj['volumeOfSideChains']]]])
                zeros=np.zeros((1,1,9))
                 ## build Ys
                if(finalYarr is None):
                    finalYarr=BuildVectorY(chain.id,res.id)
                else:
                    finalYarr=np.append(finalYarr,BuildVectorY(chain.id,res.id), axis=0)
                #buildXs
                for x in range(20):
                    if x == 7:
                        finalArr=np.append(finalArr,resarr, axis=1)
                    elif x==0:
                        finalArr=np.append(zeros,zeros, axis=1)
                    else:
                        finalArr=np.append(finalArr,zeros,  axis=1)
            elif resname == 'HIS':
                obj=aapo['H']
                resarr=np.array([[[obj['averageMass'],obj['hydrogenBond'],obj['hydrophilicity'],obj['hydrophobicity'],obj['netChargeIndexOfSideChains'],obj['polarity'],obj['polarizability'],obj['solventAccessibleSurfaceArea'],obj['volumeOfSideChains']]]])
                zeros=np.zeros((1,1,9))
                 ## build Ys
                if(finalYarr is None):
                    finalYarr=BuildVectorY(chain.id,res.id)
                else:
                    finalYarr=np.append(finalYarr,BuildVectorY(chain.id,res.id), axis=0)
                #buildXs
                for x in range(20):
                    if x == 8:
                        finalArr=np.append(finalArr,resarr, axis=1)
                    elif x==0:
                        finalArr=np.append(zeros,zeros, axis=1)
                    else:
                        finalArr=np.append(finalArr,zeros,  axis=1)
            elif resname == 'ILE':
                obj=aapo['I']
                resarr=np.array([[[obj['averageMass'],obj['hydrogenBond'],obj['hydrophilicity'],obj['hydrophobicity'],obj['netChargeIndexOfSideChains'],obj['polarity'],obj['polarizability'],obj['solventAccessibleSurfaceArea'],obj['volumeOfSideChains']]]])
                zeros=np.zeros((1,1,9))
                 ## build Ys
                if(finalYarr is None):
                    finalYarr=BuildVectorY(chain.id,res.id)
                else:
                    finalYarr=np.append(finalYarr,BuildVectorY(chain.id,res.id), axis=0)
                #buildXs
                for x in range(20):
                    if x == 9:
                        finalArr=np.append(finalArr,resarr, axis=1)
                    elif x==0:
                        finalArr=np.append(zeros,zeros, axis=1)
                    else:
                        finalArr=np.append(finalArr,zeros,  axis=1)
            elif resname == 'LEU':
                obj=aapo['L']
                resarr=np.array([[[obj['averageMass'],obj['hydrogenBond'],obj['hydrophilicity'],obj['hydrophobicity'],obj['netChargeIndexOfSideChains'],obj['polarity'],obj['polarizability'],obj['solventAccessibleSurfaceArea'],obj['volumeOfSideChains']]]])
                zeros=np.zeros((1,1,9))
                 ## build Ys
                if(finalYarr is None):
                    finalYarr=BuildVectorY(chain.id,res.id)
                else:
                    finalYarr=np.append(finalYarr,BuildVectorY(chain.id,res.id), axis=0)
                #buildXs
                for x in range(20):
                    if x == 10:
                        finalArr=np.append(finalArr,resarr, axis=1)
                    elif x==0:
                        finalArr=np.append(zeros,zeros, axis=1)
                    else:
                        finalArr=np.append(finalArr,zeros,  axis=1)
            elif resname == 'LYS':
                obj=aapo['K']
                resarr=np.array([[[obj['averageMass'],obj['hydrogenBond'],obj['hydrophilicity'],obj['hydrophobicity'],obj['netChargeIndexOfSideChains'],obj['polarity'],obj['polarizability'],obj['solventAccessibleSurfaceArea'],obj['volumeOfSideChains']]]])
                zeros=np.zeros((1,1,9))
                 ## build Ys
                if(finalYarr is None):
                    finalYarr=BuildVectorY(chain.id,res.id)
                else:
                    finalYarr=np.append(finalYarr,BuildVectorY(chain.id,res.id), axis=0)
                #buildXs
                for x in range(20):
                    if x == 11:
                        finalArr=np.append(finalArr,resarr, axis=1)
                    elif x==0:
                        finalArr=np.append(zeros,zeros, axis=1)
                    else:
                        finalArr=np.append(finalArr,zeros,  axis=1)
            elif resname == 'MET':
                obj=aapo['M']
                resarr=np.array([[[obj['averageMass'],obj['hydrogenBond'],obj['hydrophilicity'],obj['hydrophobicity'],obj['netChargeIndexOfSideChains'],obj['polarity'],obj['polarizability'],obj['solventAccessibleSurfaceArea'],obj['volumeOfSideChains']]]])
                zeros=np.zeros((1,1,9))
                 ## build Ys
                if(finalYarr is None):
                    finalYarr=BuildVectorY(chain.id,res.id)
                else:
                    finalYarr=np.append(finalYarr,BuildVectorY(chain.id,res.id), axis=0)
                #buildXs
                for x in range(20):
                    if x == 12:
                        finalArr=np.append(finalArr,resarr, axis=1)
                    elif x==0:
                        finalArr=np.append(zeros,zeros, axis=1)
                    else:
                        finalArr=np.append(finalArr,zeros,  axis=1)
            elif resname == 'PHE':
                obj=aapo['F']
                resarr=np.array([[[obj['averageMass'],obj['hydrogenBond'],obj['hydrophilicity'],obj['hydrophobicity'],obj['netChargeIndexOfSideChains'],obj['polarity'],obj['polarizability'],obj['solventAccessibleSurfaceArea'],obj['volumeOfSideChains']]]])
                zeros=np.zeros((1,1,9))
                 ## build Ys
                if(finalYarr is None):
                    finalYarr=BuildVectorY(chain.id,res.id)
                else:
                    finalYarr=np.append(finalYarr,BuildVectorY(chain.id,res.id), axis=0)
                #buildXs
                for x in range(20):
                    if x == 13:
                        finalArr=np.append(finalArr,resarr, axis=1)
                    elif x==0:
                        finalArr=np.append(zeros,zeros, axis=1)
                    else:
                        finalArr=np.append(finalArr,zeros,  axis=1)
            elif resname == 'PRO':
                obj=aapo['P']
                resarr=np.array([[[obj['averageMass'],obj['hydrogenBond'],obj['hydrophilicity'],obj['hydrophobicity'],obj['netChargeIndexOfSideChains'],obj['polarity'],obj['polarizability'],obj['solventAccessibleSurfaceArea'],obj['volumeOfSideChains']]]])
                zeros=np.zeros((1,1,9))
                 ## build Ys
                if(finalYarr is None):
                    finalYarr=BuildVectorY(chain.id,res.id)
                else:
                    finalYarr=np.append(finalYarr,BuildVectorY(chain.id,res.id), axis=0)
                
                for x in range(20):
                    if x == 14:
                        finalArr=np.append(finalArr,resarr, axis=1)
                    elif x==0:
                        finalArr=np.append(zeros,zeros, axis=1)
                    else:
                        finalArr=np.append(finalArr,zeros,  axis=1)
            elif resname == 'SER':
                obj=aapo['S']
                resarr=np.array([[[obj['averageMass'],obj['hydrogenBond'],obj['hydrophilicity'],obj['hydrophobicity'],obj['netChargeIndexOfSideChains'],obj['polarity'],obj['polarizability'],obj['solventAccessibleSurfaceArea'],obj['volumeOfSideChains']]]])
                zeros=np.zeros((1,1,9))
                 ## build Ys
                if(finalYarr is None):
                    finalYarr=BuildVectorY(chain.id,res.id)
                else:
                    finalYarr=np.append(finalYarr,BuildVectorY(chain.id,res.id), axis=0)
                #buildXs
                for x in range(20):
                    if x == 15:
                        finalArr=np.append(finalArr,resarr, axis=1)
                    elif x==0:
                        finalArr=np.append(zeros,zeros, axis=1)
                    else:
                        finalArr=np.append(finalArr,zeros,  axis=1)
            elif resname == 'THR':
                obj=aapo['T']
                resarr=np.array([[[obj['averageMass'],obj['hydrogenBond'],obj['hydrophilicity'],obj['hydrophobicity'],obj['netChargeIndexOfSideChains'],obj['polarity'],obj['polarizability'],obj['solventAccessibleSurfaceArea'],obj['volumeOfSideChains']]]])
                zeros=np.zeros((1,1,9))
                 ## build Ys
                if(finalYarr is None):
                    finalYarr=BuildVectorY(chain.id,res.id)
                else:
                    finalYarr=np.append(finalYarr,BuildVectorY(chain.id,res.id), axis=0)
                #buildXs
                for x in range(20):
                    if x == 16:
                        finalArr=np.append(finalArr,resarr, axis=1)
                    elif x==0:
                        finalArr=np.append(zeros,zeros, axis=1)
                    else:
                        finalArr=np.append(finalArr,zeros,  axis=1)
            elif resname == 'TRP':
                obj=aapo['W']
                resarr=np.array([[[obj['averageMass'],obj['hydrogenBond'],obj['hydrophilicity'],obj['hydrophobicity'],obj['netChargeIndexOfSideChains'],obj['polarity'],obj['polarizability'],obj['solventAccessibleSurfaceArea'],obj['volumeOfSideChains']]]])
                zeros=np.zeros((1,1,9))
                 ## build Ys
                if(finalYarr is None):
                    finalYarr=BuildVectorY(chain.id,res.id)
                else:
                    finalYarr=np.append(finalYarr,BuildVectorY(chain.id,res.id), axis=0)
                #buildXs
                for x in range(20):
                    if x == 17:
                        finalArr=np.append(finalArr,resarr, axis=1)
                    elif x==0:
                        finalArr=np.append(zeros,zeros, axis=1)
                    else:
                        finalArr=np.append(finalArr,zeros,  axis=1)
            elif resname == 'TYR':
                obj=aapo['Y']
                resarr=np.array([[[obj['averageMass'],obj['hydrogenBond'],obj['hydrophilicity'],obj['hydrophobicity'],obj['netChargeIndexOfSideChains'],obj['polarity'],obj['polarizability'],obj['solventAccessibleSurfaceArea'],obj['volumeOfSideChains']]]])
                zeros=np.zeros((1,1,9))
                 ## build Ys
                if(finalYarr is None):
                    finalYarr=BuildVectorY(chain.id,res.id)
                else:
                    finalYarr=np.append(finalYarr,BuildVectorY(chain.id,res.id), axis=0)
                #buildXs
                for x in range(20):
                    if x == 18:
                        finalArr=np.append(finalArr,resarr, axis=1)
                    elif x==0:
                        finalArr=np.append(zeros,zeros, axis=1)
                    else:
                        finalArr=np.append(finalArr,zeros,  axis=1)
            elif resname == 'VAL':
                obj=aapo['V']
                resarr=np.array([[[obj['averageMass'],obj['hydrogenBond'],obj['hydrophilicity'],obj['hydrophobicity'],obj['netChargeIndexOfSideChains'],obj['polarity'],obj['polarizability'],obj['solventAccessibleSurfaceArea'],obj['volumeOfSideChains']]]])
                zeros=np.zeros((1,1,9))
                 ## build Ys
                if(finalYarr is None):
                    finalYarr=BuildVectorY(chain.id,res.id)
                else:
                    finalYarr=np.append(finalYarr,BuildVectorY(chain.id,res.id), axis=0)
                #buildXs
                for x in range(20):
                    if x == 19:
                        finalArr=np.append(finalArr,resarr, axis=1)
                    elif x==0:
                        finalArr=np.append(zeros,zeros, axis=1)
                    else:
                        finalArr=np.append(finalArr,zeros,  axis=1)
            if chainarr is None:
                chainarr=finalArr
            else:
                if finalArr is None:
                    print("haha i got none")
                else:
                    #print(chainarr)
                    #print('===================')
                    #print(finalArr)
                    chainarr=np.append(chainarr,finalArr, axis=0)
        print(chainarr)
        save(filename+'-'+chain.id+'-x-.npy',chainarr)
        print(finalYarr)
        save(filename+'-'+chain.id+'-y-.npy',chainarr)
        print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")

haha i got none
haha i got none
haha i got none
haha i got none
haha i got none
haha i got none
haha i got none
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0