In [1]:
import tensorflow as tf
import numpy as np

#testing stuff
data_np=np.array([0,1,2,3,4,5,6,7,8,8], np.float32)
data_np

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 8.], dtype=float32)

In [2]:
#testing stuff
data_tf=tf.convert_to_tensor(data_np,np.float32)

sess = tf.InteractiveSession()
print(data_tf.eval())
sess.close()

[0. 1. 2. 3. 4. 5. 6. 7. 8. 8.]


In [3]:

# univariate data preparation
from numpy import array
 
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)
 
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# summarize the data
for i in range(len(X)):
	print(X[i], y[i])

n_features = 1
#reshape from [sample timesteps] to [sample timesteps features]
X=X.reshape((X.shape[0],X.shape[1],n_features))

print(X)

(array([10, 20, 30]), 40)
(array([20, 30, 40]), 50)
(array([30, 40, 50]), 60)
(array([40, 50, 60]), 70)
(array([50, 60, 70]), 80)
(array([60, 70, 80]), 90)
[[[10]
  [20]
  [30]]

 [[20]
  [30]
  [40]]

 [[30]
  [40]
  [50]]

 [[40]
  [50]
  [60]]

 [[50]
  [60]
  [70]]

 [[60]
  [70]
  [80]]]


In [4]:
#import all things needed for tensorflow LSTM network
#this is for predicting the next number
from tensorflow.keras.models import Sequential #Sequential model
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Flatten #CNN
from tensorflow.keras.layers import TimeDistributed #CNN
from tensorflow.keras.layers import Conv1D       #CNN
from tensorflow.keras.layers import MaxPooling1D #CNN

In [5]:
#vanilla LSTM


model = Sequential()
model.add(LSTM(50, activation = 'relu', input_shape=(n_steps,n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

#fitting the model
model.fit(X,y,epochs=200,verbose=1)

print('training done')
#demonstrate prediction
x_input = array([70,80,90])
x_input=x_input.reshape((1,n_steps, n_features))
yhat = model.predict(x_input,verbose=1)
print(yhat)

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/200
6/6 [==============================] - 1s 129ms/sample - loss: 5710.3833
Epoch 2/200
6/6 [==============================] - 0s 2ms/sample - loss: 5619.9155
Epoch 3/200
6/6 [==============================] - 0s 721us/sample - loss: 5529.7891
Epoch 4/200
6/6 [==============================] - 0s 2ms/sample - loss: 5440.5557
Epoch 5/200
6/6 [==============================] - 0s 1ms/sample - loss: 5351.9683
Epoch 6/200
6/6 [==============================] - 0s 1ms/sample - loss: 5263.5200
Epoch 7/200
6/6 [==============================] - 0s 1ms/sample - loss: 5174.7007
Epoch 8/200
6/6 [==============================] - 0s 1ms/sample - loss: 5084.7026
Epoch 9/200
6/6 [==============================] - 0s 1ms/sample - loss: 4994.2876
Epoch 10/200
6/6 [===================

Epoch 92/200
6/6 [==============================] - 0s 3ms/sample - loss: 7.4527
Epoch 93/200
6/6 [==============================] - 0s 952us/sample - loss: 7.4351
Epoch 94/200
6/6 [==============================] - 0s 956us/sample - loss: 7.3086
Epoch 95/200
6/6 [==============================] - 0s 998us/sample - loss: 7.0200
Epoch 96/200
6/6 [==============================] - 0s 3ms/sample - loss: 6.7243
Epoch 97/200
6/6 [==============================] - 0s 2ms/sample - loss: 6.5302
Epoch 98/200
6/6 [==============================] - 0s 2ms/sample - loss: 6.3633
Epoch 99/200
6/6 [==============================] - 0s 3ms/sample - loss: 6.1167
Epoch 100/200
6/6 [==============================] - 0s 2ms/sample - loss: 5.8526
Epoch 101/200
6/6 [==============================] - 0s 3ms/sample - loss: 5.6403
Epoch 102/200
6/6 [==============================] - 0s 1ms/sample - loss: 5.4677
Epoch 103/200
6/6 [==============================] - 0s 5ms/sample - loss: 5.2663
Epoch 104/200
6/6 

Epoch 192/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.0126
Epoch 193/200
6/6 [==============================] - 0s 998us/sample - loss: 0.0118
Epoch 194/200
6/6 [==============================] - 0s 1ms/sample - loss: 0.0109
Epoch 195/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.0102
Epoch 196/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.0095
Epoch 197/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.0090
Epoch 198/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.0084
Epoch 199/200
6/6 [==============================] - 0s 3ms/sample - loss: 0.0079
Epoch 200/200
6/6 [==============================] - 0s 1ms/sample - loss: 0.0073
training done
1/1 [==============================] - 0s 195ms/sample
[[101.926926]]


In [6]:
#Stacked LSTM

# define model
model1 = Sequential()
model1.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(n_steps, n_features)))
model1.add(LSTM(50, activation='relu'))
model1.add(Dense(1))
model1.compile(optimizer='adam', loss='mse')
# fit model
model1.fit(X, y, epochs=200, verbose=1)
# demonstrate prediction
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model1.predict(x_input, verbose=1)
print(yhat)

Epoch 1/200
6/6 [==============================] - 1s 204ms/sample - loss: 4364.6963
Epoch 2/200
6/6 [==============================] - 0s 2ms/sample - loss: 4300.6187
Epoch 3/200
6/6 [==============================] - 0s 3ms/sample - loss: 4230.2397
Epoch 4/200
6/6 [==============================] - 0s 2ms/sample - loss: 4163.7632
Epoch 5/200
6/6 [==============================] - 0s 2ms/sample - loss: 4097.8638
Epoch 6/200
6/6 [==============================] - 0s 1ms/sample - loss: 4030.2551
Epoch 7/200
6/6 [==============================] - 0s 3ms/sample - loss: 3959.4729
Epoch 8/200
6/6 [==============================] - 0s 3ms/sample - loss: 3884.3049
Epoch 9/200
6/6 [==============================] - 0s 2ms/sample - loss: 3803.9084
Epoch 10/200
6/6 [==============================] - 0s 3ms/sample - loss: 3716.6643
Epoch 11/200
6/6 [==============================] - 0s 3ms/sample - loss: 3622.8408
Epoch 12/200
6/6 [==============================] - 0s 3ms/sample - loss: 3520.7971

Epoch 101/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.1862
Epoch 102/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.1685
Epoch 103/200
6/6 [==============================] - 0s 1ms/sample - loss: 0.1502
Epoch 104/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.1329
Epoch 105/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.1188
Epoch 106/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.1082
Epoch 107/200
6/6 [==============================] - 0s 3ms/sample - loss: 0.0995
Epoch 108/200
6/6 [==============================] - 0s 1ms/sample - loss: 0.0936
Epoch 109/200
6/6 [==============================] - 0s 3ms/sample - loss: 0.0895
Epoch 110/200
6/6 [==============================] - 0s 3ms/sample - loss: 0.0844
Epoch 111/200
6/6 [==============================] - 0s 3ms/sample - loss: 0.0787
Epoch 112/200
6/6 [==============================] - 0s 3ms/sample - loss: 0.0735
Epoch 113/200
6/

1/1 [==============================] - 0s 174ms/sample
[[102.825615]]


In [7]:
#Bidirectional LSTM
# define model
model2 = Sequential()
model2.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(n_steps, n_features)))
model2.add(Dense(1))
model2.compile(optimizer='adam', loss='mse')
# fit model
model2.fit(X, y, epochs=200, verbose=1)
# demonstrate prediction
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model2.predict(x_input, verbose=1)
print(yhat)

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Epoch 1/200
6/6 [==============================] - 1s 210ms/sample - loss: 5182.0493
Epoch 2/200
6/6 [==============================] - 0s 2ms/sample - loss: 5101.8086
Epoch 3/200
6/6 [==============================] - 0s 2ms/sample - loss: 5022.0249
Epoch 4/200
6/6 [==============================] - 0s 3ms/sample - loss: 4943.7231
Epoch 5/200
6/6 [==============================] - 0s 2ms/sample - loss: 4865.2598
Epoch 6/200
6/6 [==============================] - 0s 3ms/sample - loss: 4784.5645
Epoch 7/200
6/6 [==============================] - 0s 1ms/sample - loss: 4703.0435
Epoch 8/200
6/6 [==============================] - 0s 1ms/sampl

Epoch 88/200
6/6 [==============================] - 0s 3ms/sample - loss: 2.4009
Epoch 89/200
6/6 [==============================] - 0s 2ms/sample - loss: 2.0897
Epoch 90/200
6/6 [==============================] - 0s 3ms/sample - loss: 1.8130
Epoch 91/200
6/6 [==============================] - 0s 2ms/sample - loss: 1.6526
Epoch 92/200
6/6 [==============================] - 0s 2ms/sample - loss: 1.5826
Epoch 93/200
6/6 [==============================] - 0s 2ms/sample - loss: 1.5315
Epoch 94/200
6/6 [==============================] - 0s 2ms/sample - loss: 1.4478
Epoch 95/200
6/6 [==============================] - 0s 3ms/sample - loss: 1.3247
Epoch 96/200
6/6 [==============================] - 0s 3ms/sample - loss: 1.2033
Epoch 97/200
6/6 [==============================] - 0s 3ms/sample - loss: 1.1226
Epoch 98/200
6/6 [==============================] - 0s 2ms/sample - loss: 1.0924
Epoch 99/200
6/6 [==============================] - 0s 2ms/sample - loss: 1.0920
Epoch 100/200
6/6 [=========

6/6 [==============================] - 0s 2ms/sample - loss: 0.0154
Epoch 189/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.0147
Epoch 190/200
6/6 [==============================] - 0s 3ms/sample - loss: 0.0140
Epoch 191/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.0133
Epoch 192/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.0127
Epoch 193/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.0121
Epoch 194/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.0115
Epoch 195/200
6/6 [==============================] - 0s 3ms/sample - loss: 0.0110
Epoch 196/200
6/6 [==============================] - 0s 3ms/sample - loss: 0.0105
Epoch 197/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.0100
Epoch 198/200
6/6 [==============================] - 0s 3ms/sample - loss: 0.0095
Epoch 199/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.0090
Epoch 200/200
1/1 [===========

In [8]:
#CNN-LSTM
n_steps = 4
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# reshape from [samples, timesteps] into [samples, subsequences, timesteps, features]
n_features = 1
n_seq = 2
n_steps = 2
X = X.reshape((X.shape[0], n_seq, n_steps, n_features))
# define model
model3 = Sequential()
model3.add(TimeDistributed(Conv1D(filters=64, kernel_size=1, activation='relu'), input_shape=(None, n_steps, n_features)))
model3.add(TimeDistributed(MaxPooling1D(pool_size=2)))
model3.add(TimeDistributed(Flatten()))
model3.add(LSTM(50, activation='relu'))
model3.add(Dense(1))
model3.compile(optimizer='adam', loss='mse')
# fit model
model3.fit(X, y, epochs=500, verbose=1)
# demonstrate prediction
x_input = array([60, 70, 80, 90])
x_input = x_input.reshape((1, n_seq, n_steps, n_features))
yhat = model3.predict(x_input, verbose=0)
print(yhat)

Epoch 1/500
5/5 [==============================] - 1s 203ms/sample - loss: 5429.8999
Epoch 2/500
5/5 [==============================] - 0s 963us/sample - loss: 5177.7783
Epoch 3/500
5/5 [==============================] - 0s 2ms/sample - loss: 4936.3213
Epoch 4/500
5/5 [==============================] - 0s 1ms/sample - loss: 4700.1865
Epoch 5/500
5/5 [==============================] - 0s 1ms/sample - loss: 4463.8936
Epoch 6/500
5/5 [==============================] - 0s 1ms/sample - loss: 4235.7983
Epoch 7/500
5/5 [==============================] - 0s 2ms/sample - loss: 4041.3105
Epoch 8/500
5/5 [==============================] - 0s 3ms/sample - loss: 3862.3843
Epoch 9/500
5/5 [==============================] - 0s 2ms/sample - loss: 3699.6470
Epoch 10/500
5/5 [==============================] - 0s 1ms/sample - loss: 3545.2200
Epoch 11/500
5/5 [==============================] - 0s 4ms/sample - loss: 3399.2266
Epoch 12/500
5/5 [==============================] - 0s 3ms/sample - loss: 3272.87

Epoch 101/500
5/5 [==============================] - 0s 2ms/sample - loss: 25.7385
Epoch 102/500
5/5 [==============================] - 0s 5ms/sample - loss: 25.7134
Epoch 103/500
5/5 [==============================] - 0s 4ms/sample - loss: 25.6587
Epoch 104/500
5/5 [==============================] - 0s 3ms/sample - loss: 25.4926
Epoch 105/500
5/5 [==============================] - 0s 1ms/sample - loss: 25.2565
Epoch 106/500
5/5 [==============================] - 0s 3ms/sample - loss: 25.0777
Epoch 107/500
5/5 [==============================] - 0s 2ms/sample - loss: 25.0825
Epoch 108/500
5/5 [==============================] - 0s 2ms/sample - loss: 24.9249
Epoch 109/500
5/5 [==============================] - 0s 1ms/sample - loss: 24.9787
Epoch 110/500
5/5 [==============================] - 0s 1ms/sample - loss: 25.0128
Epoch 111/500
5/5 [==============================] - 0s 2ms/sample - loss: 24.9943
Epoch 112/500
5/5 [==============================] - 0s 2ms/sample - loss: 24.9344
Epoc

Epoch 200/500
5/5 [==============================] - 0s 2ms/sample - loss: 9.0645
Epoch 201/500
5/5 [==============================] - 0s 2ms/sample - loss: 8.7359
Epoch 202/500
5/5 [==============================] - 0s 2ms/sample - loss: 8.4255
Epoch 203/500
5/5 [==============================] - 0s 1ms/sample - loss: 8.0728
Epoch 204/500
5/5 [==============================] - 0s 3ms/sample - loss: 7.6626
Epoch 205/500
5/5 [==============================] - 0s 2ms/sample - loss: 7.2291
Epoch 206/500
5/5 [==============================] - 0s 2ms/sample - loss: 6.8948
Epoch 207/500
5/5 [==============================] - 0s 1ms/sample - loss: 6.4704
Epoch 208/500
5/5 [==============================] - 0s 3ms/sample - loss: 6.1456
Epoch 209/500
5/5 [==============================] - 0s 4ms/sample - loss: 5.7941
Epoch 210/500
5/5 [==============================] - 0s 2ms/sample - loss: 5.4451
Epoch 211/500
5/5 [==============================] - 0s 1ms/sample - loss: 5.1228
Epoch 212/500
5/

Epoch 300/500
5/5 [==============================] - 0s 2ms/sample - loss: 0.0311
Epoch 301/500
5/5 [==============================] - 0s 4ms/sample - loss: 0.0302
Epoch 302/500
5/5 [==============================] - 0s 3ms/sample - loss: 0.0294
Epoch 303/500
5/5 [==============================] - 0s 2ms/sample - loss: 0.0289
Epoch 304/500
5/5 [==============================] - 0s 2ms/sample - loss: 0.0285
Epoch 305/500
5/5 [==============================] - 0s 3ms/sample - loss: 0.0282
Epoch 306/500
5/5 [==============================] - 0s 3ms/sample - loss: 0.0278
Epoch 307/500
5/5 [==============================] - 0s 2ms/sample - loss: 0.0275
Epoch 308/500
5/5 [==============================] - 0s 2ms/sample - loss: 0.0272
Epoch 309/500
5/5 [==============================] - 0s 3ms/sample - loss: 0.0269
Epoch 310/500
5/5 [==============================] - 0s 3ms/sample - loss: 0.0266
Epoch 311/500
5/5 [==============================] - 0s 3ms/sample - loss: 0.0263
Epoch 312/500
5/

Epoch 400/500
5/5 [==============================] - 0s 3ms/sample - loss: 0.0111
Epoch 401/500
5/5 [==============================] - 0s 3ms/sample - loss: 0.0109
Epoch 402/500
5/5 [==============================] - 0s 3ms/sample - loss: 0.0108
Epoch 403/500
5/5 [==============================] - 0s 3ms/sample - loss: 0.0107
Epoch 404/500
5/5 [==============================] - 0s 2ms/sample - loss: 0.0106
Epoch 405/500
5/5 [==============================] - 0s 3ms/sample - loss: 0.0105
Epoch 406/500
5/5 [==============================] - 0s 3ms/sample - loss: 0.0104
Epoch 407/500
5/5 [==============================] - 0s 3ms/sample - loss: 0.0103
Epoch 408/500
5/5 [==============================] - 0s 3ms/sample - loss: 0.0102
Epoch 409/500
5/5 [==============================] - 0s 3ms/sample - loss: 0.0101
Epoch 410/500
5/5 [==============================] - 0s 3ms/sample - loss: 0.0100
Epoch 411/500
5/5 [==============================] - 0s 4ms/sample - loss: 0.0099
Epoch 412/500
5/

Epoch 500/500
5/5 [==============================] - 0s 3ms/sample - loss: 0.0036
[[102.587654]]
